[build]
    publish = "public/"
    command = "npm run build && npm run build:fonts && npm run build:views"
[build.environment]
    NODE_ENV = "production"

# proxy api requests
[[redirects]]
    from = "/api/*"
    to = "https://smartbirds.org/api/:splat"
    status = 200

# proxy statistics
[[redirects]]
    from = "/*.json"
    to = "https://smartbirds.org/:splat"
    status = 200

# SPA routing
[[redirects]]
    from = "*"
    to = "/index.html"
    status = 200
