[build]
    publish = "public/"
    command = "npm run build && npm run build:fonts && npm run build:views && npm run test:ci"
[build.environment]
    STATS_PREFIX = "/stats"

[dev]
    command = "npm run start"
    port = 9966
    publish = "public/"

# proxy api requests
[[redirects]]
    from = "/api/*"
    to = "https://smartbirds.org/api/:splat"
    status = 200

# proxy statistics
[[redirects]]
    from = "/stats/*"
    to = "https://smartbirds.org/:splat"
    status = 200

# SPA routing
[[redirects]]
    from = "*"
    to = "/index.html"
    status = 200
