[build]
    publish = "public/"
    command = "npm run build && npm run build:fonts && npm run build:views"
[build.environment]
    NODE_ENV = "production"
    TRANSLATION_PREFIX = "/api/staging/i18n"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
    from = "https://smartbirds.netlify.com/*"
    to = "https://next.smartbirds.org/:splat"
    status = 301
    force = true
[[redirects]]
    from = "https://smartbirds-staging.netlify.com/*"
    to = "https://staging.smartbirds.org/:splat"
    status = 301
    force = true

# proxy staging api requests
[[redirects]]
    from = "/api/staging/*"
    to = "https://smartbirds.org/api/:splat"
    status = 200
# proxy production api requests
[[redirects]]
    from = "/api/*"
    to = "https://smartbirds-staging.herokuapp.com/api/:splat"
    status = 200

# proxy staging statistics
[[redirects]]
    from = "/stats/staging/*"
    to = "https://smartbirds-staging.herokuapp.com/:splat"
    status = 200
# proxy production statistics
[[redirects]]
    from = "/stats/*"
    to = "https://smartbirds.org/:splat"
    status = 200

# SPA routing
[[redirects]]
    from = "*"
    to = "/index.html"
    status = 200
