[build]
    publish = "public/"
    command = "npm run build && npm run build:fonts && npm run build:views"
[build.environment]
    NODE_ENV = "production"
    STATS_PREFIX = "/stats"

# proxy api requests
[[redirects]]
    from = "/api/*"
    to = "https://smartbirds.org/api/:splat"
    status = 200

# proxy statistics
[[redirects]]
    from = "/stats/*"
    to = "https://smartbirds.org/:splat"
    status = 200

# SPA routing
[[redirects]]
    from = "*"
    to = "/index.html"
    status = 200

# Redirect default Netlify subdomain to primary domain
[[redirects]]
    from = "https://smartbirds.netlify.com/*"
    to = "https://next.smartbirds.org/:splat"
    status = 301
    force = true
