var angular = require('angular')
var modulename = require('./modulename')
var states = require('./states')
var AtlasDashboardController = require('./controllers/AtlasDashboardController')
var AtlasHomeController = require('./controllers/AtlasHomeController')
var AtlasLegendDirective = require('./directives/AtlasLegendDirective')
var AtlasRequestController = require('./controllers/AtlasRequestController')
var AtlasStatsController = require('./controllers/AtlasStatsController')

module.exports = angular
  .module(modulename, [])
  .config(states)
  .controller('AtlasDashboardController', AtlasDashboardController)
  .controller('AtlasHomeController', AtlasHomeController)
  .controller('AtlasRequestController', AtlasRequestController)
  .controller('AtlasStatsController', AtlasStatsController)
  .directive('atlasLegend', AtlasLegendDirective)
