const angular = require('angular')
const modulename = require('./modulename')
const states = require('./states')
const AtlasDashboardController = require('./controllers/AtlasDashboardController')
const AtlasHomeController = require('./controllers/AtlasHomeController')
const AtlasInterestMapController = require('./controllers/AtlasInterestMapController')
const AtlasLegendDirective = require('./directives/AtlasLegendDirective')
const AtlasMissingSpeciesController = require('./controllers/AtlasMissingSpeciesController')
const AtlasModeratorProgressController = require('./controllers/AtlasModeratorProgressController')
const AtlasRequestController = require('./controllers/AtlasRequestController')
const AtlasStatsCellDirective = require('./directives/AtlasStatsCellDirective')
const AtlasStatsController = require('./controllers/AtlasStatsController')
const AtlasStatsRankingDirective = require('./directives/AtlasStatsRankingDirective')

module.exports = angular
  .module(modulename, [])
  .config(states)
  .controller('AtlasDashboardController', AtlasDashboardController)
  .controller('AtlasHomeController', AtlasHomeController)
  .controller('AtlasInterestMapController', AtlasInterestMapController)
  .controller('AtlasMissingSpeciesController', AtlasMissingSpeciesController)
  .controller('AtlasModeratorProgressController', AtlasModeratorProgressController)
  .controller('AtlasRequestController', AtlasRequestController)
  .controller('AtlasStatsController', AtlasStatsController)
  .directive('atlasLegend', AtlasLegendDirective)
  .directive('atlasStatsCell', AtlasStatsCellDirective)
  .directive('atlasStatsRanking', AtlasStatsRankingDirective)
